version: "3"

services:
  mongo:
    container_name: mongo-container
    image: mongo
    restart: unless-stopped
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: api
    build: .
    image: api
    restart: unless-stopped
    command: [
      "./wait-for-it.sh",
      "mongo-container:27017",
      "--timeout=30",
      "--",
      "npm",
      "run",
      "start:prod"
    ]

    volumes:
      - ./dist:/usr/app/api/dist
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo-container:27017/app
